export const images = {
  tobias: "/Dale Arts - Signed In – 1/pexels-tobias-bjørkli-2236382.png",
  tobias2: "/Dale Arts - Signed In – 1/pexels-tobias-bjørkli-2236382@2x.png",
  steve: "/Dale Arts - Signed In – 1/pexels-steve-johnson-1269968.png",
  steve2: "/Dale Arts - Signed In – 1/pexels-steve-johnson-1269968@2x.png",
  pixabay: "/Dale Arts - Signed In – 1/pexels-pixabay-164455.png",
  pixabay2: "/Dale Arts - Signed In – 1/pexels-pixabay-164455@2x.png",
  max: "/Dale Arts - Signed In – 1/pexels-max-vakhtbovych-6782342.png",
  max2: "/Dale Arts - Signed In – 1/pexels-max-vakhtbovych-6782342@2x.png",
  imag: "/Dale Arts - Signed In – 1/pexels-imad-clicks-9810659.png",
  imag2: "/Dale Arts - Signed In – 1/pexels-imad-clicks-9810659@2x.png",
  muleba: "/Dale Arts - Signed In – 1/pexels-humphrey-muleba-2045248.png",
  muleba2: "/Dale Arts - Signed In – 1/pexels-humphrey-muleba-2045248@2x.png",
  genero: "/Dale Arts - Signed In – 1/pexels-genaro-servín-763210.png",
  genero2: "/Dale Arts - Signed In – 1/pexels-genaro-servín-763210@2x.png",
  fiona: "/Dale Arts - Signed In – 1/pexels-fiona-art-5022849.png",
  fiona2: "/Dale Arts - Signed In – 1/pexels-fiona-art-5022849@2x.png",
  katrina: "/Dale Arts - Signed In – 1/pexels-ekaterina-12203460.png",
  katrina2: "/Dale Arts - Signed In – 1/pexels-ekaterina-12203460@2x.png",
  antoni: "/Dale Arts - Signed In – 1/pexels-antoni-shkraba-4442102.png",
  antoni2: "/Dale Arts - Signed In – 1/pexels-antoni-shkraba-4442102@2x.png",
  antoni3: "/Dale Arts - Signed In – 1/pexels-antoni-shkraba-4442005.png",
  antoni4: "/Dale Arts - Signed In – 1/pexels-antoni-shkraba-4442005@2x.png",
  andrea: "/Dale Arts - Signed In – 1/pexels-andrea-piacquadio-3771118.png",
  andrea2: "/Dale Arts - Signed In – 1/pexels-andrea-piacquadio-3771118@2x.png",
  anastasia: "/Dale Arts - Signed In – 1/pexels-anastasia-shuraeva-4406721.png",
  anastasia2:
    "/Dale Arts - Signed In – 1/pexels-anastasia-shuraeva-4406721@2x.png",
  ali: "/Dale Arts - Signed In – 1/pexels-ali-pazani-2613260.png",
  ali2: "/Dale Arts - Signed In – 1/pexels-ali-pazani-2613260@2x.png",
  post: "/Dale Arts - Signed In – 1/post.svg",
  post1: "/Dale Arts - Signed In – 1/post2.svg",
  post2: "/Dale Arts - Signed In – 1/post3.svg",
  post3: "/Dale Arts - Signed In – 1/post4.svg",
  comment: "/Dale Arts - Signed In – 1/comment-1.svg",
  comment1: "/Dale Arts - Signed In – 1/comment.svg",
  component: "/Dale Arts - Signed In – 1/Component 32.svg",
  component1: "/Dale Arts - Signed In – 1/Component 39 (2).svg",
  favourite: "/Dale Arts - Signed In – 1/favorite.svg",
  heart1: "/Dale Arts - Signed In – 1/heart-1.svg",
  heart2: "/Dale Arts - Signed In – 1/heart-2.svg",
  heart3: "/Dale Arts - Signed In – 1/heart-3.svg",
  heart4: "/Dale Arts - Signed In – 1/heart-4.svg",
  heart: "/Dale Arts - Signed In – 1/heart.svg",
  home: "/Dale Arts - Signed In – 1/home.svg",
  image: "/Dale Arts - Signed In – 1/Image 39.png",
  image39: "/Dale Arts - Signed In – 1/Image 39@2x.png",
  image40: "/Dale Arts - Signed In – 1/Image 40.png",
  image40x2: "/Dale Arts - Signed In – 1/Image 40@2x.png",
  message1: "/Dale Arts - Signed In – 1/message-1.svg",
  message: "/Dale Arts - Signed In – 1/message.svg",
  notification: "/Dale Arts - Signed In – 1/notification.svg",
  profile: "/Dale Arts - Signed In – 1/profile.svg",
  setting: "/Dale Arts - Signed In – 1/setting.svg",
  share1: "/Dale Arts - Signed In – 1/share-1.svg",
  share: "/Dale Arts - Signed In – 1/share.svg",
  star: "/Dale Arts - Signed In – 1/star.svg",
  star1: "/Dale Arts - Signed In – 1/star-1.svg",
  wallet: "/Dale Arts - Signed In – 1/wallet.svg",
  logout: "/Dale Arts - Signed In – 1/logout.svg",
};
